// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed-admin.js",
  },
  datasource: {
    url:
      process.env["MYSQL_DATABASE_URL"] ||
      process.env["DATABASE_URL"] ||
      process.env["MYSQL_URL"] ||
      process.env["DB_URL"],
  },
});
